[package]
name = "barqflow-flow"
version.workspace = true
edition.workspace = true

[dependencies]
barqflow-core = { path = "../core" }
petgraph.workspace  = true
rhai.workspace      = true
serde.workspace     = true
serde_json.workspace = true
thiserror.workspace = true
regex = "1"
chrono = { version = "0.4", features = ["serde"] }
urlencoding = "2"
tracing = "0.1"
hex = "0.4"
md-5 = "0.10"
sha2 = "0.10"
