[package]
name = "barqflow-exec"
version.workspace = true
edition.workspace = true

[dependencies]
barqflow-core = { path = "../core" }
barqflow-flow = { path = "../flow" }
barqflow-registry = { path = "../registry" }
tokio.workspace     = true
tracing.workspace   = true
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
async-trait.workspace = true
bytes.workspace = true
tempfile.workspace = true
chrono = { version = "0.4.43", features = ["serde"] }
petgraph.workspace = true
