[package]
name = "barqflow-nodes"
version.workspace = true
edition.workspace = true

[dependencies]
barqflow-core     = { path = "../core" }
barqflow-registry = { path = "../registry" }
reqwest.workspace   = true
rhai = { workspace = true, features = ["serde"] }
tokio.workspace     = true
serde.workspace     = true
serde_json.workspace = true
tokio-cron-scheduler.workspace = true
async-trait.workspace = true
base64 = "0.22.1"
sqlx = { workspace = true, features = ["postgres"] }

[dev-dependencies]
mockito = "1.7.2"
