use barqflow_core::schema::INodeExecutionData;
use barqflow_core::types::RunId;
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::{HashMap, VecDeque};
use std::sync::Arc;
use tokio::sync::RwLock;

/// Default maximum number of in-flight execution states kept in memory.
pub const DEFAULT_STATE_CAPACITY: usize = 512;

/// Enum describing the current status of an execution run
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(rename_all = "camelCase")]
pub enum ExecutionStatus {
    #[default]
    New,
    Running,
    Waiting,
    Error,
    Success,
    Crashed,
    Canceled,
}

/// Represents the data generated or processed by a single node during execution
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ITaskData {
    /// Timestamp when the node started processing
    pub start_time: i64,
    /// Duration of the execution in ms
    pub execution_time: i64,
    /// Original array of outputs generated by this node
    pub data: HashMap<usize, Vec<INodeExecutionData>>,
    /// Error message if the node failed
    #[serde(skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
}

/// Wrapper storing task data for all nodes historically executed in a run.
/// The key is the node name.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(transparent)]
#[derive(Default)]
pub struct IRunExecutionData(pub HashMap<String, Vec<ITaskData>>);

/// Core Model persisting the full state of a workflow execution run
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExecutionState {
    pub id: RunId,
    pub workflow_id: String,
    pub status: ExecutionStatus,
    /// Data of the workflow context that triggered this execution
    pub started_at: DateTime<Utc>,
    /// Stopped or completed execution time
    #[serde(skip_serializing_if = "Option::is_none")]
    pub stopped_at: Option<DateTime<Utc>>,
    /// Results computed by nodes in this execution
    pub data: IRunExecutionData,
    /// Indicates whether execution is tracking manually by the user
    #[serde(default)]
    pub manual: bool,
}

impl ExecutionState {
    pub fn new(workflow_id: &str, manual: bool) -> Self {
        Self {
            id: RunId::new(),
            workflow_id: workflow_id.to_string(),
            status: ExecutionStatus::New,
            started_at: Utc::now(),
            stopped_at: None,
            data: IRunExecutionData::default(),
            manual,
        }
    }

    pub fn mark_finished(&mut self, success: bool) {
        self.stopped_at = Some(Utc::now());
        self.status = if success {
            ExecutionStatus::Success
        } else {
            ExecutionStatus::Error
        };
    }
}

struct BoundedStateStore {
    map: HashMap<RunId, ExecutionState>,
    /// Insertion-order queue used for FIFO eviction when capacity is exceeded.
    insertion_order: VecDeque<RunId>,
    capacity: usize,
}

impl BoundedStateStore {
    fn new(capacity: usize) -> Self {
        Self {
            map: HashMap::with_capacity(capacity),
            insertion_order: VecDeque::with_capacity(capacity),
            capacity,
        }
    }

    fn insert(&mut self, id: RunId, state: ExecutionState) {
        if !self.map.contains_key(&id) {
            if self.map.len() >= self.capacity {
                if let Some(oldest) = self.insertion_order.pop_front() {
                    self.map.remove(&oldest);
                }
            }
            self.insertion_order.push_back(id);
        }
        self.map.insert(id, state);
    }

    fn remove(&mut self, id: &RunId) -> Option<ExecutionState> {
        let removed = self.map.remove(id);
        if removed.is_some() {
            self.insertion_order.retain(|k| k != id);
        }
        removed
    }

    fn get(&self, id: &RunId) -> Option<&ExecutionState> {
        self.map.get(id)
    }

    fn values(&self) -> impl Iterator<Item = &ExecutionState> {
        self.map.values()
    }

    fn len(&self) -> usize {
        self.map.len()
    }
}

/// Manages execution states for active workflow runs.
///
/// Bounded to `capacity` entries; oldest entries are evicted FIFO when full.
pub struct ExecutionStateManager {
    states: Arc<RwLock<BoundedStateStore>>,
    metrics: Arc<RwLock<ExecutionMetrics>>,
}

#[derive(Debug, Clone, Default)]
pub struct ExecutionMetrics {
    pub nodes_executed: u64,
    pub data_processed_bytes: u64,
}

impl ExecutionStateManager {
    pub fn new() -> Self {
        Self::with_capacity(DEFAULT_STATE_CAPACITY)
    }

    pub fn with_capacity(capacity: usize) -> Self {
        Self {
            states: Arc::new(RwLock::new(BoundedStateStore::new(capacity))),
            metrics: Arc::new(RwLock::new(ExecutionMetrics::default())),
        }
    }

    pub async fn create(&self, workflow_id: &str, manual: bool) -> ExecutionState {
        let state = ExecutionState::new(workflow_id, manual);
        let id = state.id;
        self.states.write().await.insert(id, state.clone());
        state
    }

    pub async fn get(&self, run_id: &RunId) -> Option<ExecutionState> {
        self.states.read().await.get(run_id).cloned()
    }

    pub async fn update(&self, run_id: &RunId, state: ExecutionState) {
        self.states.write().await.insert(*run_id, state);
    }

    pub async fn remove(&self, run_id: &RunId) -> Option<ExecutionState> {
        self.states.write().await.remove(run_id)
    }

    pub async fn list_active(&self) -> Vec<ExecutionState> {
        self.states.read().await.values().cloned().collect()
    }

    pub async fn len(&self) -> usize {
        self.states.read().await.len()
    }

    pub async fn increment_nodes_executed(&self) {
        self.metrics.write().await.nodes_executed += 1;
    }

    pub async fn add_data_processed(&self, bytes: u64) {
        self.metrics.write().await.data_processed_bytes += bytes;
    }

    pub async fn get_metrics(&self) -> ExecutionMetrics {
        self.metrics.read().await.clone()
    }
}

impl Default for ExecutionStateManager {
    fn default() -> Self {
        Self::new()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_execution_state_creation() {
        let state = ExecutionState::new("test-workflow-123", true);
        assert_eq!(state.workflow_id, "test-workflow-123");
        assert_eq!(state.status, ExecutionStatus::New);
        assert!(state.manual);
    }

    #[test]
    fn test_mark_finished() {
        let mut state = ExecutionState::new("wf", false);
        state.mark_finished(true);
        assert_eq!(state.status, ExecutionStatus::Success);
        assert!(state.stopped_at.is_some());

        let mut fail_state = ExecutionState::new("wf", false);
        fail_state.mark_finished(false);
        assert_eq!(fail_state.status, ExecutionStatus::Error);
    }

    #[tokio::test]
    async fn test_execution_state_manager() {
        let manager = ExecutionStateManager::new();

        let state = manager.create("test-wf", true).await;
        assert_eq!(state.workflow_id, "test-wf");

        let retrieved = manager.get(&state.id).await.unwrap();
        assert_eq!(retrieved.id, state.id);

        manager.increment_nodes_executed().await;
        manager.add_data_processed(100).await;

        let metrics = manager.get_metrics().await;
        assert_eq!(metrics.nodes_executed, 1);
        assert_eq!(metrics.data_processed_bytes, 100);
    }

    #[tokio::test]
    async fn test_list_active() {
        let manager = ExecutionStateManager::new();

        manager.create("wf1", false).await;
        manager.create("wf2", true).await;

        let active = manager.list_active().await;
        assert_eq!(active.len(), 2);
    }

    #[tokio::test]
    async fn test_capacity_evicts_oldest_entry() {
        let manager = ExecutionStateManager::with_capacity(2);

        let first = manager.create("wf1", false).await;
        manager.create("wf2", false).await;
        // inserting a third entry should evict `first`
        manager.create("wf3", false).await;

        assert_eq!(manager.len().await, 2);
        assert!(manager.get(&first.id).await.is_none(), "oldest entry should be evicted");
    }

    #[tokio::test]
    async fn test_remove_shrinks_store() {
        let manager = ExecutionStateManager::new();

        let state = manager.create("wf1", false).await;
        assert_eq!(manager.len().await, 1);

        manager.remove(&state.id).await;
        assert_eq!(manager.len().await, 0);
    }
}
